# Generated by Django 6.0.4 on 2026-08-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_in_game', to='authentication.profile')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_in_game', to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(choices=[('PLAYER1', 'PLAYER1'), ('PLAYER2', 'PLAYER2')], max_length=10)),
                ('move', models.CharField(choices=[('H1V1', 'H1V1'), ('H2V1', 'H2V1'), ('H3V1', 'H3V1'), ('H1V2', 'H1V2'), ('H2V2', 'H2V2'), ('H3V2', 'H3V2'), ('H1V3', 'H1V3'), ('H2V3', 'H2V3'), ('H3V3', 'H3V3')], max_length=4)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_played', to='logic.game')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.PositiveIntegerField(default=0)),
                ('player2_score', models.PositiveIntegerField(default=0)),
                ('winner', models.CharField(choices=[('PLAYER1', 'PLAYER1'), ('PLAYER2', 'PLAYER2'), ('DRAW', 'DRAW')], default='DRAW')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='logic.game')),
            ],
        ),
    ]
